#ifndef __IMAGE_MSG_PRV_H__
#define __IMAGE_MSG_PRV_H__


#ifdef  __cplusplus
    extern  "C"{
#endif
    

typedef enum
{
	IDSCAM_IMG_MSG_CAPTURE = 1,
	IDSCAM_IMG_MSG_RECORED_START,
	IDSCAM_IMG_MSG_RECORED_STOP,
	IDSCAM_IMG_MSG_GET_SCAN_PIC_NUM,
	IDSCAM_IMG_MSG_SCAN_PIC,
    
    IDSCAM_IMG_MSG_ENABLE_AE,
    IDSCAM_IMG_MSG_GET_ENABLE_AE,
    
    IDSCAM_IMG_MSG_AE_SET_TARGET_RATIO,
    IDSCAM_IMG_MSG_AE_GET_TARGET_RATIO,

    IDSCAM_IMG_MSG_ENABLE_AWB,
    IDSCAM_IMG_MSG_GET_ENABLE_AWB,
    
    IDSCAM_IMG_MSG_AWB_SET_ONE_PUSH,
    IDSCAM_IMG_MSG_AWB_GET_ONE_PUSH,
    
    IDSCAM_IMG_MSG_ANTIFLICKER,
    IDSCAM_IMG_MSG_GET_ANTIFLICKER,

    IDSCAM_IMG_MSG_CONTRAST,
    IDSCAM_IMG_MSG_GET_CONTRAST,

    IDSCAM_IMG_MSG_SATURATION,
    IDSCAM_IMG_MSG_GET_SATURATION,
    
    IDSCAM_IMG_MSG_BRIGHTNESS,
    IDSCAM_IMG_MSG_GET_BRIGHTNESS,
	IDSCAM_IMG_MSG_HUE,
    IDSCAM_IMG_MSG_GET_HUE,
	
    IDSCAM_IMG_MSG_SHARPNESS,
	IDSCAM_IMG_MSG_GET_SHARPNESS,
    
    IDSCAM_IMG_MSG_DENOISE,
    IDSCAM_IMG_MSG_GET_DENOISE,

    IDSCAM_IMG_MSG_AWB_SET_RED_GAIN,
    IDSCAM_IMG_MSG_AWB_GET_RED_GAIN,
    
    IDSCAM_IMG_MSG_AWB_SET_GREEN_GAIN,
    IDSCAM_IMG_MSG_AWB_GET_GREEN_GAIN,
    
    IDSCAM_IMG_MSG_AWB_SET_BLUE_GAIN,
    IDSCAM_IMG_MSG_AWB_GET_BLUE_GAIN,
    
    IDSCAM_IMG_MSG_AWB_SET_COLORTEMP,
    IDSCAM_IMG_MSG_AWB_GET_COLORTEMP,

    IDSCAM_IMG_MSG_MIRROR,
    IDSCAM_IMG_MSG_FLIP,
    
    IDSCAM_IMG_MSG_SET_BW_MODE,
	IDSCAM_IMG_MSG_SENSOR_HDR_OP_MODE,
    
    IDSCAM_IMG_MSG_GET_SDCARD_STATE,
    
    IDSCAM_EVENT_MSG_SDCARD_STATE,
    IDSCAM_EVENT_GET_CAPTURE_FILENAME,
	IDSCAM_EVENT_GET_RECORED_FILENAME,
    
    IDSCAM_IMG_MSG_GET_CAPTURE_POINT,
    IDSCAM_IMG_MSG_RESET_ISP, 
    IDSCAM_EVENT_MSG_UPDATE_SET_ENBALE,
    IDSCAM_EVENT_MSG_UPDATE_GET_VUALE,
    IDSCAM_IMG_MSG_EXIT,
}img_msg_cmd_t;

int     Image_Msg_Start(void);
int     Image_Msg_Send(img_msg_cmd_t cmd,void *data,int len);
int     Image_Msg_Get(img_msg_cmd_t cmd,void *data,int len);
int     Image_Msg_Proess(img_msg_cmd_t cmd,void *dat,int len);

#ifdef  __cplusplus
}
#endif

    

#endif
