#ifndef __XW_WINDOW_XY_DF_H__
#define __XW_WINDOW_XY_DF_H__

//dedfine   main menu window
#define XW_MAIN_WINDOW_X           1504             
#define XW_MAIN_WINDOW_Y           150




//deinfine line set button
#define XW_LINE_SHOW_WINDOW_X       XW_MAIN_WINDOW_X +  224
#define XW_LINE_SHOW_WINDOW_Y       XW_MAIN_WINDOW_Y +  669
#define XW_LINE_CHOICE_WINDOW_X      XW_MAIN_WINDOW_X + 35
#define XW_LINE_CHOICE_WINDOW_Y      XW_MAIN_WINDOW_Y + 669
#define XW_LINE_LOCK_WINDOW_X        XW_MAIN_WINDOW_X + 129       
#define XW_LINE_LOCK_WINDOW_Y        XW_MAIN_WINDOW_Y + 669    

#define XW_LINE_SET_SIZE_WINDOW_X      XW_MAIN_WINDOW_X +   129
#define XW_LINE_SET_SIZE_WINDOW_Y      XW_MAIN_WINDOW_Y +   747
#define XW_LINE_SET_COLOR_WINDOW_X       XW_MAIN_WINDOW_X + 35   
#define XW_LINE_SET_COLOR_WINDOW_Y       XW_MAIN_WINDOW_Y + 747   

#define XW_LINE_SELECT_LINE_WINDOW_X      XW_MAIN_WINDOW_X + 225 
#define XW_LINE_SELECT_LINE_WINDOW_Y      XW_MAIN_WINDOW_Y + 747  

#define XW_LINE_CLAER_WINDOW_X          XW_MAIN_WINDOW_X +  319
#define XW_LINE_CLAER_WINDOW_Y          XW_MAIN_WINDOW_Y + 745

#define XW_LINE_SAVE_WINDOW_X           XW_MAIN_WINDOW_X + 319
#define XW_LINE_SAVE_WINDOW_Y           XW_MAIN_WINDOW_Y + 669


//define video param settings
#define XW_VIDEO_ZOOZ_BOOST_WINDOW_X      XW_MAIN_WINDOW_X + 0   
#define XW_VIDEO_ZOOZ_BOOST_WINDOW_Y        XW_MAIN_WINDOW_Y + 0 


#define XW_VIDEO_FILP_WINDOW_X            XW_MAIN_WINDOW_X + 33   
#define XW_VIDEO_FILP_WINDOW_Y              XW_MAIN_WINDOW_Y + 593 

#define XW_VIDEO_MIRROR_WINDOW_X            XW_MAIN_WINDOW_X + 128 
#define XW_VIDEO_MIRROR_WINDOW_Y            XW_MAIN_WINDOW_Y + 593


#define XW_VIDEO_NIGHGT_WINDOW_X          XW_MAIN_WINDOW_X + 224
#define XW_VIDEO_NIGHGT_WINDOW_Y            XW_MAIN_WINDOW_Y + 593

#define XW_VIDEO_HDR_WINDOW_X        XW_MAIN_WINDOW_X + 319
#define XW_VIDEO_HDR_WINDOW_Y        XW_MAIN_WINDOW_Y + 593


//#define XW_VIDEO_DAY_WINDOW_X        XW_MAIN_WINDOW_X + 0 
//#define XW_VIDEO_DAY_WINDOW_Y        XW_MAIN_WINDOW_Y + 0 



//#define XW_VIDEO_UNLOCK_WINDOW_X     XW_MAIN_WINDOW_X + 0 
//#define XW_VIDEO_UNLOCK_WINDOW_Y     XW_MAIN_WINDOW_Y + 0 




//define date text window id 
#define XW_DATE_YEAR_WINDOW_X        XW_MAIN_WINDOW_X + 116  
#define XW_DATE_YEAR_WINDOW_Y        XW_MAIN_WINDOW_Y + 498



#define XW_DATE_MONN_WINDOW_X         XW_MAIN_WINDOW_X + 173       
#define XW_DATE_MONN_WINDOW_Y          XW_MAIN_WINDOW_Y + 498     


#define XW_DATE_DAY_WINDOW_X            XW_MAIN_WINDOW_X + 212
#define XW_DATE_DAY_WINDOW_Y            XW_MAIN_WINDOW_Y + 498


#define XW_DATE_HOUR_WINDOW_X               XW_MAIN_WINDOW_X + 264
#define XW_DATE_HOUR_WINDOW_Y               XW_MAIN_WINDOW_Y + 498


#define XW_DATE_MIN_WINDOW_X               XW_MAIN_WINDOW_X + 303
#define XW_DATE_MIN_WINDOW_Y              XW_MAIN_WINDOW_Y + 498


#define XW_DATE_SEC_WINDOW_X               XW_MAIN_WINDOW_X + 341
#define XW_DATE_SEC_WINDOW_Y                XW_MAIN_WINDOW_Y + 498

#define XW_DATE_SET_UP_WINDOW_X            XW_MAIN_WINDOW_X + 116 
#define XW_DATE_SET_UP_WINDOW_Y            XW_MAIN_WINDOW_Y + 479


#define XW_DATE_SET_DOWN_WINDOW_X          XW_MAIN_WINDOW_X + 116
#define XW_DATE_SET_DOWN_WINDOW_Y          XW_MAIN_WINDOW_Y + 539

#define XW_DATE_SET_WINDOW_X          XW_MAIN_WINDOW_X + 3
#define XW_DATE_SET_WINDOW_Y          XW_MAIN_WINDOW_Y + 479





//define isp set window id
#define XW_ISP_COLOR_TEMP_WINDOW_X         XW_MAIN_WINDOW_X + 193
#define XW_ISP_COLOR_TEMP_WINDOW_Y         XW_MAIN_WINDOW_Y + 439
#define XW_ISP_COLOR_TEMP_TEXT_WINDOW_X    XW_MAIN_WINDOW_X + 350
#define XW_ISP_COLOR_TEMP_TEXT_WINDOW_Y    XW_MAIN_WINDOW_Y + 434



#define XW_ISP_BLUE_WINDOW_X            XW_MAIN_WINDOW_X + 193
#define XW_ISP_BLUE_WINDOW_Y            XW_MAIN_WINDOW_Y + 409
#define XW_ISP_BLUE_TEXT_WINDOW_X       XW_MAIN_WINDOW_X + 350
#define XW_ISP_BLUE_TEXT_WINDOW_Y       XW_MAIN_WINDOW_Y + 404

   

#define XW_ISP_RED_WINDOW_X             XW_MAIN_WINDOW_X + 193
#define XW_ISP_RED_WINDOW_Y             XW_MAIN_WINDOW_Y + 347   //347
#define XW_ISP_RED_TEXT_WINDOW_X        XW_MAIN_WINDOW_X + 350
#define XW_ISP_RED_TEXT_WINDOW_Y        XW_MAIN_WINDOW_Y + 344    //344


#define XW_ISP_GREEN_WINDOW_X           XW_MAIN_WINDOW_X + 193
#define XW_ISP_GREEN_WINDOW_Y           XW_MAIN_WINDOW_Y + 379   //379


#define XW_ISP_GREEN_TEXT_WINDOW_X      XW_MAIN_WINDOW_X + 350
#define XW_ISP_GREEN_TEXT_WINDOW_Y      XW_MAIN_WINDOW_Y + 374   //374



//freq func

#define XW_ISP_DENOISE_WINDOW_X         XW_MAIN_WINDOW_X + 193
#define XW_ISP_DENOISE_WINDOW_Y         XW_MAIN_WINDOW_Y + 317
#define XW_ISP_DENOISE_TEXT_WINDOW_X    XW_MAIN_WINDOW_X + 350
#define XW_ISP_DENOISE_TEXT_WINDOW_Y    XW_MAIN_WINDOW_Y + 312
  


#define XW_ISP_SHARPNESS_WINDOW_X           XW_MAIN_WINDOW_X + 193
#define XW_ISP_SHARPNESS_WINDOW_Y           XW_MAIN_WINDOW_Y + 287
#define XW_ISP_SHARPNESS_TEXT_WINDOW_X      XW_MAIN_WINDOW_X + 350
#define XW_ISP_SHARPNESS_TEXT_WINDOW_Y      XW_MAIN_WINDOW_Y + 282



#define XW_ISP_BRIGHTNESS_WINDOW_X         XW_MAIN_WINDOW_X + 193
#define XW_ISP_BRIGHTNESS_WINDOW_Y         XW_MAIN_WINDOW_Y + 256
#define XW_ISP_BRIGHTNESS_TEXT_WINDOW_X    XW_MAIN_WINDOW_X + 350
#define XW_ISP_BRIGHTNESS_TEXT_WINDOW_Y    XW_MAIN_WINDOW_Y + 251



#define XW_ISP_SATURATION_WINDOW_X         XW_MAIN_WINDOW_X + 193
#define XW_ISP_SATURATION_WINDOW_Y         XW_MAIN_WINDOW_Y + 225
#define XW_ISP_SATURATION_TEXT_WINDOW_X    XW_MAIN_WINDOW_X + 350
#define XW_ISP_SATURATION_TEXT_WINDOW_Y    XW_MAIN_WINDOW_Y + 220




#define XW_ISP_CONTRAST_WINDOW_X           XW_MAIN_WINDOW_X + 193
#define XW_ISP_CONTRAST_WINDOW_Y           XW_MAIN_WINDOW_Y + 195
#define XW_ISP_CONTRAST_TEXT_WINDOW_X      XW_MAIN_WINDOW_X + 350
#define XW_ISP_CONTRAST_TEXT_WINDOW_Y      XW_MAIN_WINDOW_Y + 190



//#define XW_ISP_GAMMA_WINDOW_X              XW_MAIN_WINDOW_X + 0
//#define XW_ISP_GAMMA_WINDOW_Y              XW_MAIN_WINDOW_Y + 0
//#define XW_ISP_GAMMA_TEXT_WINDOW_X         XW_MAIN_WINDOW_X + 0
//#define XW_ISP_GAMMA_TEXT_WINDOW_Y         XW_MAIN_WINDOW_Y + 0



//filck
#define XW_FILCKER_50H_WINDOW_X            XW_MAIN_WINDOW_X + 237
#define XW_FILCKER_50H_WINDOW_Y            XW_MAIN_WINDOW_Y + 124


#define XW_FILCKER_60H_WINDOW_X             XW_MAIN_WINDOW_X + 351
#define XW_FILCKER_60H_WINDOW_Y             XW_MAIN_WINDOW_Y + 124
  


#define XW_AUTO_WHITE_BALANCE_WINDOW_X      XW_MAIN_WINDOW_X + 237
#define XW_AUTO_WHITE_BALANCE_WINDOW_Y      XW_MAIN_WINDOW_Y + 92

#define XW_MANUL_WHITE_BALANCE_WINDOW_X     XW_MAIN_WINDOW_X + 352
#define XW_MANUL_WHITE_BALANCE_WINDOW_Y     XW_MAIN_WINDOW_Y + 92



#define XW_AE_MANUL_WINDOW_X                XW_MAIN_WINDOW_X + 193
#define XW_AE_MANUL_WINDOW_Y                XW_MAIN_WINDOW_Y + 62
#define XW_MANUL_EXPOUSURE_TEXT_WINDOW_X    XW_MAIN_WINDOW_X + 350
#define XW_MANUL_EXPOUSURE_TEXT_WINDOW_Y    XW_MAIN_WINDOW_Y + 55
 

#define XW_AUTO_EXPOUSURE_WINDOW_X          XW_MAIN_WINDOW_X + 237
#define XW_AUTO_EXPOUSURE_WINDOW_Y          XW_MAIN_WINDOW_Y + 26

//line menu window xy def

#define XW_LINE_RARR_WINDOW_X               10
#define XW_LINE_RARR_WINDOW_Y               10

//top MENU window xy def
#define XW_TOP_MENU_WINDOW_X                1504
#define XW_TOP_MENU_WINDOW_Y                50

//#define   snap recod set perview
#define XW_SNAP_WINDOW_X            XW_TOP_MENU_WINDOW_X + 0
#define XW_SNAP_WINDOW_Y            XW_TOP_MENU_WINDOW_Y + 1

#define XW_RECOD_WINDOW_X           XW_TOP_MENU_WINDOW_X + 107
#define XW_RECOD_WINDOW_Y           XW_TOP_MENU_WINDOW_Y + 1

#define XW_PERVIEW_WINDOW_X         XW_TOP_MENU_WINDOW_X + 214
#define XW_PERVIEW_WINDOW_Y         XW_TOP_MENU_WINDOW_Y + 1

#define XW_SET_WINDOW_X             XW_TOP_MENU_WINDOW_X + 321
#define XW_SET_WINDOW_Y             XW_TOP_MENU_WINDOW_Y + 1




//#define image  preview  window

#define XW_PERVIEW_IMAGE_ANY_WINDOW_X          400
#define XW_PERVIEW_IMAGE_ANY_WINDOW_Y          250

#define XW_PERVIEW_IMAGE_ONLY_WINDOW_X         0
#define XW_PERVIEW_IMAGE_ONLY_WINDOW_Y         0



//#define imagessege info window
#define XW_MESSAGE_PINT_TEXT_WINDOW_X          920
#define XW_MESSAGE_PINT_TEXT_WINDOW_Y          500


//define text prompt box x,y
#define XW_TEXT_PROMPT_BOX_WINDOW_X            900
#define XW_TEXT_PROMPT_BOX_WINDOW_Y            500


#define XW_TEXT_TIME_CNT_BOX_WINDOW_X               50
#define XW_TEXT_TIME_CNT_BOX_WINDOW_Y               50



#endif
