#ifndef __XW_WINDOW_XY_DF_H__
#define __XW_WINDOW_XY_DF_H__

//dedfine   main menu window
#define XW_MAIN_WINDOW_X           1504             
#define XW_MAIN_WINDOW_Y           150




//deinfine line set button
#define XW_LINE_SHOW_WINDOW_X       XW_MAIN_WINDOW_X +  225
#define XW_LINE_SHOW_WINDOW_Y       XW_MAIN_WINDOW_Y +  669
#define XW_LINE_CHOICE_WINDOW_X      XW_MAIN_WINDOW_X + 35
#define XW_LINE_CHOICE_WINDOW_Y      XW_MAIN_WINDOW_Y + 669
#define XW_LINE_LOCK_WINDOW_X        XW_MAIN_WINDOW_X + 129       
#define XW_LINE_LOCK_WINDOW_Y        XW_MAIN_WINDOW_Y + 669    

#define XW_LINE_SET_SIZE_WINDOW_X      XW_MAIN_WINDOW_X +   129
#define XW_LINE_SET_SIZE_WINDOW_Y      XW_MAIN_WINDOW_Y +   747
#define XW_LINE_SET_COLOR_WINDOW_X       XW_MAIN_WINDOW_X + 35   
#define XW_LINE_SET_COLOR_WINDOW_Y       XW_MAIN_WINDOW_Y + 747   
#define XW_LINE_SELECT_LINE_WINDOW_X      XW_MAIN_WINDOW_X + 225 
#define XW_LINE_SELECT_LINE_WINDOW_Y      XW_MAIN_WINDOW_Y + 747  

//#define XW_LINE_CHANGE_COLOR_WINDOW_X       XW_MAIN_WINDOW_X + 0 
//#define XW_LINE_CHANGE_COLOR_WINDOW_Y    XW_MAIN_WINDOW_Y + 0 

//define video advanced settings
#define XW_VIDEO_ZOOZ_LESSEN_WINDOW_X   XW_MAIN_WINDOW_X + 0 
#define XW_VIDEO_ZOOZ_LESSEN_WINDOW_Y    XW_MAIN_WINDOW_Y + 0 

#define XW_VIDEO_ZOOZ_BOOST_WINDOW_X      XW_MAIN_WINDOW_X + 0   
#define XW_VIDEO_ZOOZ_BOOST_WINDOW_Y        XW_MAIN_WINDOW_Y + 0 


#define XW_VIDEO_FILP_WINDOW_X            XW_MAIN_WINDOW_X + 0   
#define XW_VIDEO_FILP_WINDOW_Y              XW_MAIN_WINDOW_Y + 0 

#define XW_VIDEO_MIRROR_WINDOW_X            XW_MAIN_WINDOW_X + 0 
#define XW_VIDEO_MIRROR_WINDOW_Y            XW_MAIN_WINDOW_Y + 0 


#define XW_VIDEO_NIGHGT_WINDOW_X          XW_MAIN_WINDOW_X + 0 
#define XW_VIDEO_NIGHGT_WINDOW_Y            XW_MAIN_WINDOW_Y + 0 


#define XW_VIDEO_DAY_WINDOW_X        XW_MAIN_WINDOW_X + 0 
#define XW_VIDEO_DAY_WINDOW_Y        XW_MAIN_WINDOW_Y + 0 


#define XW_VIDEO_HDR_WINDOW_X        XW_MAIN_WINDOW_X + 0 
#define XW_VIDEO_HDR_WINDOW_Y        XW_MAIN_WINDOW_Y + 0 


#define XW_VIDEO_UNLOCK_WINDOW_X     XW_MAIN_WINDOW_X + 0 
#define XW_VIDEO_UNLOCK_WINDOW_Y     XW_MAIN_WINDOW_Y + 0 




//define date text window id 
#define XW_DATE_YEAR_WINDOW_X        XW_MAIN_WINDOW_X + 116  
#define XW_DATE_YEAR_WINDOW_Y        XW_MAIN_WINDOW_Y + 498



#define XW_DATE_MONN_WINDOW_X         XW_MAIN_WINDOW_X + 173       
#define XW_DATE_MONN_WINDOW_Y          XW_MAIN_WINDOW_Y + 498     


#define XW_DATE_DAY_WINDOW_X            XW_MAIN_WINDOW_X + 212
#define XW_DATE_DAY_WINDOW_Y            XW_MAIN_WINDOW_Y + 498


#define XW_DATE_HOUR_WINDOW_X               XW_MAIN_WINDOW_X + 264
#define XW_DATE_HOUR_WINDOW_Y               XW_MAIN_WINDOW_Y + 498


#define XW_DATE_MIN_WINDOW_X               XW_MAIN_WINDOW_X + 303
#define XW_DATE_MIN_WINDOW_Y              XW_MAIN_WINDOW_Y + 498


#define XW_DATE_SEC_WINDOW_X               XW_MAIN_WINDOW_X + 341
#define XW_DATE_SEC_WINDOW_Y                XW_MAIN_WINDOW_Y + 498

#define XW_DATE_SET_UP_WINDOW_X            XW_MAIN_WINDOW_X + 116 
#define XW_DATE_SET_UP_WINDOW_Y            XW_MAIN_WINDOW_Y + 479


#define XW_DATE_SET_DOWN_WINDOW_X          XW_MAIN_WINDOW_X + 116
#define XW_DATE_SET_DOWN_WINDOW_Y          XW_MAIN_WINDOW_Y + 539

#define XW_DATE_SET_WINDOW_X          XW_MAIN_WINDOW_X + 3
#define XW_DATE_SET_WINDOW_Y          XW_MAIN_WINDOW_Y + 479





//define isp set window id
#define XW_ISP_COLOR_TEMP_WINDOW_X         XW_MAIN_WINDOW_X + 0
#define XW_ISP_COLOR_TEMP_WINDOW_Y         XW_MAIN_WINDOW_Y + 0
#define XW_ISP_COLOR_TEMP_TEXT_WINDOW_X    XW_MAIN_WINDOW_Y + 0
#define XW_ISP_COLOR_TEMP_TEXT_WINDOW_Y    XW_MAIN_WINDOW_Y + 0



#define XW_ISP_BULE_WINDOW_X            XW_MAIN_WINDOW_X + 0
#define XW_ISP_BULE_WINDOW_Y            XW_MAIN_WINDOW_Y + 0
#define XW_ISP_BULE_TEXT_WINDOW_X       XW_MAIN_WINDOW_X + 0
#define XW_ISP_BULE_TEXT_WINDOW_Y       XW_MAIN_WINDOW_Y + 0

   

#define XW_ISP_RED_WINDOW_X             XW_MAIN_WINDOW_X + 0
#define XW_ISP_RED_WINDOW_Y             XW_MAIN_WINDOW_Y + 0
#define XW_ISP_RED_TEXT_WINDOW_X        XW_MAIN_WINDOW_X + 0
#define XW_ISP_RED_TEXT_WINDOW_Y        XW_MAIN_WINDOW_Y + 0
   


#define XW_ISP_DENOISE_WINDOW_X         XW_MAIN_WINDOW_X + 0
#define XW_ISP_DENOISE_WINDOW_Y         XW_MAIN_WINDOW_Y + 0
#define XW_ISP_DENOISE_TEXT_WINDOW_X    XW_MAIN_WINDOW_X + 0
#define XW_ISP_DENOISE_TEXT_WINDOW_Y    XW_MAIN_WINDOW_Y + 0
  


#define XW_ISP_SHARPNESS_WINDOW_X           XW_MAIN_WINDOW_X + 0
#define XW_ISP_SHARPNESS_WINDOW_Y           XW_MAIN_WINDOW_Y + 0
#define XW_ISP_SHARPNESS_TEXT_WINDOW_X      XW_MAIN_WINDOW_X + 0
#define XW_ISP_SHARPNESS_TEXT_WINDOW_Y      XW_MAIN_WINDOW_Y + 0



#define XW_ISP_BRIGHTNESS_WINDOW_X         XW_MAIN_WINDOW_X + 0
#define XW_ISP_BRIGHTNESS_WINDOW_Y         XW_MAIN_WINDOW_Y + 0
#define XW_ISP_BRIGHTNESS_TEXT_WINDOW_X    XW_MAIN_WINDOW_X + 0
#define XW_ISP_BRIGHTNESS_TEXT_WINDOW_Y    XW_MAIN_WINDOW_Y + 0



#define XW_ISP_SATURATION_WINDOW_X         XW_MAIN_WINDOW_X + 0
#define XW_ISP_SATURATION_WINDOW_Y         XW_MAIN_WINDOW_Y + 0
#define XW_ISP_SATURATION_TEXT_WINDOW_X    XW_MAIN_WINDOW_X + 0
#define XW_ISP_SATURATION_TEXT_WINDOW_Y    XW_MAIN_WINDOW_Y + 0




#define XW_ISP_CONTRAST_WINDOW_X           XW_MAIN_WINDOW_X + 0
#define XW_ISP_CONTRAST_WINDOW_Y           XW_MAIN_WINDOW_Y + 0
#define XW_ISP_CONTRAST_TEXT_WINDOW_X      XW_MAIN_WINDOW_X + 0
#define XW_ISP_CONTRAST_TEXT_WINDOW_Y      XW_MAIN_WINDOW_Y + 0



#define XW_ISP_GAMMA_WINDOW_X              XW_MAIN_WINDOW_X + 0
#define XW_ISP_GAMMA_WINDOW_Y              XW_MAIN_WINDOW_Y + 0
#define XW_ISP_GAMMA_TEXT_WINDOW_X         XW_MAIN_WINDOW_X + 0
#define XW_ISP_GAMMA_TEXT_WINDOW_Y         XW_MAIN_WINDOW_Y + 0



//
#define XW_FILCKER_50H_WINDOW_X            XW_MAIN_WINDOW_X + 0
#define XW_FILCKER_50H_WINDOW_Y            XW_MAIN_WINDOW_Y + 0



#define XW_FILCKER_60H_WINDOW_X             XW_MAIN_WINDOW_X + 0
#define XW_FILCKER_60H_WINDOW_Y             XW_MAIN_WINDOW_Y + 0
  


#define XW_AUTO_WHITE_BALANCE_WINDOW_X    XW_MAIN_WINDOW_X + 0
#define XW_AUTO_WHITE_BALANCE_WINDOW_Y     XW_MAIN_WINDOW_Y + 0



#define XW_AE_TARGET_WINDOW_X           XW_MAIN_WINDOW_X + 0
#define XW_AE_TARGET_WINDOW_Y            XW_MAIN_WINDOW_Y + 0
  


#define XW_AUTO_EXPOUSURE_WINDOW_X        XW_MAIN_WINDOW_X + 0
#define XW_AUTO_EXPOUSURE_WINDOW_Y         XW_MAIN_WINDOW_Y + 0

//line menu window xy def

#define XW_LINE_RARR_WINDOW_X               10
#define XW_LINE_RARR_WINDOW_Y               10

//top MENU window xy def
#define XW_TOP_MENU_WINDOW_X                1504
#define XW_TOP_MENU_WINDOW_Y                50

//#define   snap recod set perview
#define XW_SNAP_WINDOW_X            XW_TOP_MENU_WINDOW_X + 0
#define XW_SNAP_WINDOW_Y            XW_TOP_MENU_WINDOW_Y + 1

#define XW_RECOD_WINDOW_X           XW_TOP_MENU_WINDOW_X + 107
#define XW_RECOD_WINDOW_Y           XW_TOP_MENU_WINDOW_Y + 1

#define XW_PERVIEW_WINDOW_X         XW_TOP_MENU_WINDOW_X + 214
#define XW_PERVIEW_WINDOW_Y         XW_TOP_MENU_WINDOW_Y + 1

#define XW_SET_WINDOW_X             XW_TOP_MENU_WINDOW_X + 321
#define XW_SET_WINDOW_Y             XW_TOP_MENU_WINDOW_Y + 1




#endif
